### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by richardasaurus**
This was voted on but missed when creating the style guide somehow. Results:

```
10. Never put any code in the __init__.py of a module (except namespace stitching imports).
Yes
Yes
Yes
No
No
Yes
No
Yes
Yes
Yes
Yes
Yes
```

### CODE REVIEW

**Comment by wearp** [comment]
I can't help the question should of been something like "What sort of code should go in an `__init__.py` (if any at all?". I feel it's a bit leading. Basically brexit all over again.

**Comment by richardasaurus** [comment]
@wearp you sound like Hilary after she lost

**Comment by harel** [comment]
I use __init__.py to put code/base classes that relates specifically to the rest of that module/package. i feel like they belong there. if the gods didn't want us to use __init__.py they would not have put that file in our directories.

**Comment by richardasaurus** [comment]
This isn't the place to try to re-vote guys. I'm simply adding something which has already been votes on. If you want to change it, make a new poll 👍

**Pull request merged**
